trigger:
- main

variables:
  TF_VERSION: '1.6.0'
  AWS_DEFAULT_REGION: 'us-east-1'

stages:
- stage: TerraformApply
  jobs:
  - job: Terraform
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'

    - script: |
        curl -sL https://raw.githubusercontent.com/tfutils/tfenv/master/install.sh | bash
        echo 'export PATH="$HOME/.tfenv/bin:$PATH"' >> ~/.bashrc
        source ~/.bashrc
        tfenv install $TF_VERSION
        tfenv use $TF_VERSION
      displayName: 'Install Terraform with tfenv'

    - task: AWSCLI@1
      inputs:
        awsCredentials: 'aws'  # <- Your service connection name
        awsRegion: '$(AWS_DEFAULT_REGION)'
      displayName: 'Configure AWS Credentials'

    - checkout: self

    - script: terraform init
      workingDirectory: ./terraform
      displayName: 'Terraform Init'

    - script: terraform plan -out=tfplan
      workingDirectory: ./terraform
      displayName: 'Terraform Plan'

    - script: terraform apply -auto-approve tfplan
      workingDirectory: ./terraform
      displayName: 'Terraform Apply'
